### ISSUE TITLE
Error encountered on video giveaway

### ISSUE THREAD

**Issue by dziban303** [sniffingpickles/Auto-Amazon-Giveaways#4]
Bot crashed immediately after 30-sec timer expired on a video giveaway, with error message "Node is detached from document". Not sure what happened.

This was the second attempt on this giveaway. The first attempt ended with the same error message as seen on issue #3 ("pyppeteer.errors.TimeoutError: Waiting failed: timeout 30000ms exceeds.")

```E:\Auto-Amazon-Giveaways>f:\python36\python.exe give_it_away_now.py
Log into Amazon...
Processing GiveAway:  Weight Loss Cleanse Program For 15 Days - All Natural Organic - Alkaline Your Body For Healthy & Sustainable Weight Loss Detox, Digestion Support - Powerful Colon, Kidney, Liver & Bowel Cleanser
https://www.amazon.com/ga/p/ccfda0de98898097
    **** Waiting 30 seconds. ****
    **** 30 Seconds is over, Entering Contest. ****
Traceback (most recent call last):
  File "give_it_away_now.py", line 18, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "f:\python36\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "give_it_away_now.py", line 16, in main
    await do_ga_workflow(ga_page)
  File "give_it_away_now.py", line 12, in do_ga_workflow
    await ga_bot.process_giveaways(page)
  File "E:\Auto-Amazon-Giveaways\lib\giveaway.py", line 358, in process_giveaways
    await self.no_req_giveaways()
  File "E:\Auto-Amazon-Giveaways\lib\giveaway.py", line 225, in no_req_giveaways
    await enter_video.click()
  File "f:\python36\lib\site-packages\pyppeteer\element_handle.py", line 124, in click
    obj = await self._visibleCenter()
  File "f:\python36\lib\site-packages\pyppeteer\element_handle.py", line 82, in _visibleCenter
    await self._scrollIntoViewIfNeeded()
  File "f:\python36\lib\site-packages\pyppeteer\element_handle.py", line 79, in _scrollIntoViewIfNeeded
    raise ElementHandleError(error)
pyppeteer.errors.ElementHandleError: Node is detached from document
```

**Comment by sniffingpickles** [comment]
Hmm, I didn't get this issue after just forcing it to view that giveaway.  Will debug more and keep this ticket open until resolved.
